server:
  port: 8081
spring:
  application:
    name: Job
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql_host:127.0.0.1}:3306/message_job?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${mysql_username:root}
    password: ${mysql_password:root}
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接时间存货最大时间默认10分钟-600000ms
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 50
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大存活时间，0表示永久，默认30分钟--1800000ms
      max-lifetime: 180000
      # 连接超时时间
      connection-timeout: 30000
      # 测试连接是否可用
      connection-test-query: SELECT 1